apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  {{- if eq .Values.configmap.name "mongodb-configmap" }} 
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.configmap.mongo.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.configmap.mongo.password }} 
  {{- end }}
  {{- if eq .Values.configmap.name "mongo-express-configmap" }} 
  ME_CONFIG_MONGODB_SERVER: {{ .Values.configmap.mongoexpress.username }}
  ME_CONFIG_MONGODB_ADMINUSERNAME: {{ .Values.configmap.mongoexpress.password }} 
  ME_CONFIG_MONGODB_ADMINPASSWORD: {{ .Values.configmap.mongoexpress.password }} 
  {{- end }}