apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.container.port }}
        env:
        {{- if eq .Values.deployment.name "mongo" }}
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MONGO_INITDB_ROOT_PASSWORD
        {{- end }}
        {{- if eq .Values.deployment.name "mongo-express" }}
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKyRef:
                name: {{ .Values.configmap.name }}
                key: ME_CONFIG_MONGODB_SERVER
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              configMapKyRef:
                name: {{ .Values.configmap.name }}
                key: ME_CONFIG_MONGODB_ADMINUSERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              configMapKyRef:
                name: {{ .Values.configmap.name }}
                key: ME_CONFIG_MONGODB_ADMINPASSWORD
        {{- end }}